# Generated by Django 5.0.1 on 2024-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
